# Generated by Django 5.2.5 on 2025-09-06 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('condo', 'Condo'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('house', 'House'), ('townhouse', 'Townhouse'), ('bungalow', 'Bungalow'), ('co-op', 'Co-op'), ('loft', 'Loft'), ('barn', 'Barn'), ('shack', 'Shack'), ('cottage', 'Cottage'), ('parking', 'Parking')], max_length=30)),
                ('property_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_status', models.CharField(choices=[('negotiable', 'Negotiable'), ('fixed', 'Fixed')], max_length=10)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_price_status', models.CharField(choices=[('negotiable', 'Negotiable'), ('fixed', 'Fixed')], max_length=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking_spaces', models.IntegerField()),
                ('amenities', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tennant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_tennant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.property')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.property')),
            ],
        ),
    ]
