# Generated by Django 4.2.24 on 2025-10-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
