# Generated by Django 5.2.5 on 2025-09-06 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tennant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rental_tennant', to=settings.AUTH_USER_MODEL),
        ),
    ]
