# Generated by Django 4.2.24 on 2025-10-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_rename_name_unit_nickname_unit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycomplex',
            name='units',
        ),
        migrations.AddField(
            model_name='unit',
            name='complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pm.propertycomplex'),
        ),
    ]
