# Generated by Django 5.2.5 on 2025-09-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_alter_property_status_alter_property_tennant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lease',
            name='monthly_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='Pending', max_length=10),
        ),
    ]
