# Generated by Django 5.2.5 on 2025-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_alter_lease_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='Available', max_length=50),
        ),
    ]
