# Generated by Django 4.2.24 on 2025-10-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_remove_propertycomplex_units_unit_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.unit'),
        ),
    ]
