# Generated by Django 5.2.5 on 2025-09-08 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tennant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_tennant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=32)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pm.lease')),
            ],
        ),
    ]
