# Generated by Django 4.2.24 on 2025-10-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_lease_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.property'),
        ),
    ]
