# Generated by Django 5.2.5 on 2025-09-08 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_alter_property_tennant_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tennant',
        ),
        migrations.AddField(
            model_name='property',
            name='tennant',
            field=models.ManyToManyField(blank=True, related_name='rental_tennant', to=settings.AUTH_USER_MODEL),
        ),
    ]
