# Generated by Django 4.2.24 on 2025-10-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_alter_lease_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_messages', to='pm.unit'),
        ),
        migrations.AlterField(
            model_name='message',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_messages', to='pm.property'),
        ),
    ]
