# Generated by Django 5.2.5 on 2025-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_remove_property_tennant_property_tennant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], max_length=9),
        ),
    ]
