# Generated by Django 4.2.24 on 2025-10-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_message_unit_alter_message_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], default='verified', max_length=10),
        ),
    ]
