# Generated by Django 5.2.5 on 2025-09-08 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ManyToManyField(blank=True, related_name='leases', to=settings.AUTH_USER_MODEL),
        ),
    ]
