# Generated by Django 4.2.24 on 2025-10-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt',
        ),
    ]
