# Generated by Django 5.2.5 on 2025-09-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_remove_lease_tenant_lease_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rent_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_price_status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tennant',
        ),
    ]
