# Generated by Django 4.2.24 on 2025-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_remove_expense_description_remove_expense_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
    ]
