# Generated by Django 5.2.5 on 2025-09-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_alter_lease_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_status',
        ),
    ]
