# Generated by Django 4.2.24 on 2025-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_expense_notes_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=9),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=9),
        ),
    ]
