# Generated by Django 4.2.24 on 2025-10-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0011_alter_property_status_alter_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.unit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pm.property'),
        ),
    ]
