# Generated by Django 4.2.24 on 2025-10-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_problem_unit_alter_problem_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
