# Generated by Django 5.2.5 on 2025-09-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_messages', to='pm.lease'),
        ),
    ]
