# Generated by Django 4.2.24 on 2025-10-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pm.lease'),
        ),
    ]
