# Generated by Django 4.2.24 on 2025-10-02 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_document_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b8c951f-9ac1-4dab-98f2-8449a7d76da0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86163a42-da75-458c-b34b-76d532d3c693'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e640bebf-0ad6-4e1f-a6da-3c1d74a94726'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
