# Generated by Django 4.2.24 on 2025-10-04 15:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0016_alter_document_id_alter_lease_id_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c1972fc-b988-4cc6-8266-6d7c079cb4d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72969f61-7a63-4f71-a235-66dbabc72c12'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d47a675c-d260-43cb-815b-41d2a4b12569'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
